version: '3.7'
services:
  frontend:
    container_name: blog-frontend
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - NODE_ENV=development
networks:
  default:
    name: blog
